---
- name: Enable incoming connection
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{item}}"
    jump: ACCEPT
  with_items:
    - ssh
    - http
    - https
- name: Enable traffic for outgoing connection
  iptables:
    chain: INPUT
    protocol: tcp
    source_port: "{{item}}"
    destination_port: 1024:65535
    jump: ACCEPT
  with_items:
    - http
    - https
    - git
- name: Enable dns traffic
  iptables:
    chain: INPUT
    protocol: udp
    source_port: domain
    jump: ACCEPT
- name: Enable incoming icmp echo
  iptables:
    chain: INPUT
    protocol: icmp
    # Эта штука работает только в ansible 2.2
    #icmp_type: echo
    jump: ACCEPT
- name: Disable all other incoming packets
  command: iptables -P INPUT DROP
  # Эта штука работает в ansible 2.2
  #iptables:
  #  chain: INPUT
  #  policy: DROP
- name: Save ruleset
  shell: iptables-save > /etc/iptables.rules
