---
- name: Install nginx
  apt: "name='nginx' state=present force=yes"
- name: Remove unneeded files
  file: "path={{nginx_sites_dir}}/default state=absent"
- name: copy nginx config of project
  template: "src=roles/nginx/templates/nginx.j2 dest={{nginx_conf_dir}}/{{project_name}}.conf"
- name: copy nginx conf from sites-available to sites-enabled
  file: "src={{nginx_conf_dir}}/{{project_name}}.conf dest={{nginx_sites_dir}}/{{project_name}}.conf state=link"
- name: create project log directory
  file: "path={{project_dir}}/logs state=directory"
- name: start nginx
  service: "name=nginx state=started"

