---
- hosts: laweb
  vars:
    project_name: laweb
    project_dir: /usr/share/{{project_name}}
  vars_files:
    - /etc/ansible/{{project_name}}.yml
  roles:
    - django
    - laweb
    - uwsgi
    - nginx
