# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-25 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Creation date')),
                ('group', models.CharField(max_length=200)),
                ('subgroup', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('shortname', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lawe.Account')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lawe.Account')),
            ],
        ),
    ]
