# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 17:15
''' Миграция для дат в транзакции '''
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	''' Автоматическая подстановка даты в транзакции '''
	dependencies = [
		('lawe', '0002_auto_20161227_2005'),
	]

	operations = [
		migrations.AlterField(
			model_name='transaction',
			name='date',
			field=models.DateTimeField(auto_now=True, verbose_name='date'),
		),
	]
