# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 20:23
''' Миграция для белых списков пользователей '''

from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	''' К счету добавились списки пользователей, которые могут им пользоваться '''

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('lawe', '0003_auto_20170102_1715'),
	]

	operations = [
		migrations.AddField(
			model_name='account',
			name='allow_users',
			field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
		),
	]
