# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 19:04
''' Новые миграции на юниты '''
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
	''' Миграция '''
	dependencies = [
		('lawe', '0004_account_allow_users'),
	]

	operations = [
		migrations.AlterModelOptions(
			name='account',
			options={'verbose_name': 'Счет', 'verbose_name_plural': 'Счета'},
		),
		migrations.AlterModelOptions(
			name='transaction',
			options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
		),
		migrations.AddField(
			model_name='transaction',
			name='unit',
			field=models.CharField(
				choices=[('RUB', 'Рубли'), ('KG', 'Килограммы')],
				default='RUB',
				max_length=3,
				verbose_name='Единица измерения'
			),
		),
		migrations.AlterField(
			model_name='transaction',
			name='amount',
			field=models.IntegerField(verbose_name='Сумма'),
		),
		migrations.AlterField(
			model_name='transaction',
			name='credit',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name='+',
				to='lawe.Account',
				verbose_name='Кредит'
			),
		),
		migrations.AlterField(
			model_name='transaction',
			name='date',
			field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
		),
		migrations.AlterField(
			model_name='transaction',
			name='debit',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name='+',
				to='lawe.Account',
				verbose_name='Дебет'
			),
		),
		migrations.AlterField(
			model_name='transaction',
			name='description',
			field=models.CharField(max_length=200, verbose_name='Описание'),
		),
	]
