# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 20:47
''' Миграция '''
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
	''' Удаляем единицы измерений из счетов '''
	dependencies = [
		('lawe', '0005_auto_20170421_1904'),
	]

	operations = [
		migrations.RemoveField(
			model_name='account',
			name='unit',
		),
	]
