# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 19:37
''' Миграция '''
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	''' Добавляем опциональные поля '''
	dependencies = [
		('lawe', '0006_remove_account_unit'),
	]

	operations = [
		migrations.AlterField(
			model_name='account',
			name='group',
			field=models.CharField(blank=True, max_length=200, verbose_name='Основная группа'),
		),
		migrations.AlterField(
			model_name='account',
			name='name',
			field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
		),
		migrations.AlterField(
			model_name='account',
			name='subgroup',
			field=models.CharField(blank=True, max_length=200, verbose_name='Подгруппа'),
		),
		migrations.AlterField(
			model_name='transaction',
			name='description',
			field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
		),
	]
