# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 20:00
''' opdate автоматически не заполняется '''
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
	''' Нельзя сделать автоматически заполняемое поле и при этом редактируемое в админке '''
	dependencies = [
		('lawe', '0009_auto_20170425_1949'),
	]

	operations = [
		migrations.AlterField(
			model_name='transaction',
			name='opdate',
			field=models.DateField(null=True, verbose_name='Дата проведения'),
		),
	]
