---
- name: Install uwsgi package
  apt: "name={{item}} state=present force=yes"
  with_items:
    - uwsgi
    - uwsgi-plugin-python3
- name: Copy uwsgi config of project
  template: "src=roles/uwsgi/templates/{{project_name}}.j2 dest=/etc/uwsgi/apps-available/{{project_name}}.ini"
- name: Copy uwsgi conf from apps-available to apps-enabled
  file: "src=/etc/uwsgi/apps-available/{{project_name}}.ini dest=/etc/uwsgi/apps-enabled/{{project_name}}.ini state=link"
- name: Restart uwsgi service
  service: "name=uwsgi state=restarted"
